### ISSUE TITLE
URLs doesn't follow REST Principles.

### ISSUE THREAD

**Issue by ravindra-fueled** [amitshekhariitbhu/node_app#1]
`/getAllUsers/{pageNumber}` should be GET `/users`
`/getAnUser/{userId}` should be GET `/users/{userId}`
`/createAnUser` should be POST `/users` 

Please check this presentation for more information https://speakerdeck.com/ravidsrk/restful-api-using-node-dot-js-with-express

**Comment by amitshekhariitbhu** [comment]
Yes I know that but I had created this when I started node last year and the link is distributed for testing API at various place like on my medium blogs and all. So I had not changed it today.

**Comment by amitshekhariitbhu** [comment]
Anyway I will check the presentation and learn from it.
